
# high level client
spring:
  elasticsearch:
    rest:
      uris: http://ailuoli.cn:9200
      username: elastic
      password: coding
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: coding
    url: jdbc:mysql://120.53.234.127:1234/blog?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=GMT%2B8
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.learn.elastic.model
  mapper-locations: classpath:/mapper/*.xml

